@startuml
class BallCollisionHandler {
    - isTouchingFloor : bool = false
    - OnCollisionEnter(collision:Collision) : void
    - OnCollisionExit(collision:Collision) : void
    + IsTouchingFloor() : bool
}
MonoBehaviour <|-- BallCollisionHandler
@enduml
