@startuml
interface IBallManager {
    CreateBall(prefab:GameObject, parent:Transform, position:Vector3) : Ball
    DestroyBall(ballGameObject:GameObject) : void
    CheckBallContactTime(ballGameObject:GameObject, currentContactTime:float) : float
}
class BallManager {
    + CreateBall(playableBallPrefab:GameObject, ballParentTransform:Transform, position:Vector3) : Ball
    + DestroyBall(ballGameObject:GameObject) : void
    + CheckBallContactTime(ballGameObject:GameObject, currentContactTime:float) : float
}
IBallManager <|-- BallManager
@enduml
