@startuml
class GamePresenter {
    - Awake() : void
    - Start() : void
    - Update() : void
    - Bind() : void
    - InitializeDependencies() : void
    - InitializeView() : void
    - InitializeGameManager() : void
    - LoadGameData() : void
    - StartGame() : void
    - RestartGame() : void
    - Back2Menu() : void
    - QuitGame() : void
}
MonoBehaviour <|-- GamePresenter
GamePresenter --> "_viewComponent" MonoBehaviour
GamePresenter --> "_playableBallPrefab" GameObject
GamePresenter --> "_ballParentTransform" Transform
GamePresenter --> "_gameOverPanel" Transform
GamePresenter --> "_view" IGameView
GamePresenter --> "_input" IGameInput
GamePresenter --> "_stageTiltController" IGameMove
GamePresenter --> "_gameModel" IGameModel
GamePresenter --> "_ballManager" IBallManager
GamePresenter --> "_stageManager" IStageManager
GamePresenter --> "_scoreManager" IScoreManager
GamePresenter --> "_gameManager" GameManager
@enduml
