@startuml
class Game {
    + IsGameStarted : bool <<get>> <<set>> = false
    + RequiredContactTime : float <<get>> = 3.0f
    + GameOverTime : float <<get>> = 30.0f
    + GameTime : float <<get>> <<set>> = 0.0f
    + Ball1ContactTime : float <<get>> <<set>> = 0.0f
    + Ball2ContactTime : float <<get>> <<set>> = 0.0f
    + SaveFilePath : string <<get>> <<set>>
}
class "List`1"<T> {
}
Game o-> "TopTimes<float>" "List`1"
Game --> "ScoreData" ScoreData
@enduml
